
services:
  token-manager:
    build: .
    image: samply/token-manager
    ports:
      - 3030:3030
    environment:
      - BEAM_URL=http://proxy1:8081
      - BEAM_ID=app1.proxy1.broker
      - BEAM_SECRET=App1Secret
      - TOKEN_MANAGER_DB_URL=./file.db
    networks:
      - dev_default
      - default


networks:
  dev_default:
    external:
      true
