
services:
  token-manager:
    build: .
    image: samply/token-manager
    ports:
      - 3030:3030
    env_file:
      - .env
    # Override env
    environment:
      - BEAM_URL=http://proxy1:8081
    networks:
      - dev_default
      - default


networks:
  dev_default:
    external:
      true
