
name: Build with rust and docker

on:
  workflow_run:
    workflows: [Check Rust]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    # This workflow defines how a maven package is built, tested and published.
    # Visit: https://github.com/samply/github-workflows/blob/develop/.github/workflows/docker-ci.yml, for more information
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      # The Docker Hub Repository you want eventually push to, e.g samply/share-client
      image-name: "samply/token-manager"
      push-to: "dockerhub"
      # image-tag-suffix: ${{ matrix.features && format('-{0}', matrix.features) }}
      # Define special prefixes for docker tags. They will prefix each images tag.
      # image-tag-prefix: "foo"
      # Define the build context of your image, typically default '.' will be enough
      # build-context: '.'
      # Define the Dockerfile of your image, typically default './Dockerfile' will be enough
      build-file: './Dockerfile'
      # NOTE: This doesn't work currently
      # A list of build arguments, passed to the docker build
      # build-args: |
      #   FEATURE=-${{ matrix.features }}
      # Define the target platforms of the docker build (default "linux/amd64,linux/arm64/v8")
      # build-platforms: "linux/amd64"
      # If your actions generate an artifact in a previous build step, you can tell this workflow to download it
      # artifact-name: '*'
    # This passes the secrets from calling workflow to the called workflow
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
