name: Check Rust

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  PROFILE: release

jobs:
  pre-check:
    name: Security, License Check
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1

  rust:
    name: Build (Rust)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo check --all-features
          cargo test --all-features
          cargo build --release
